move up upload whl

diff --git a/.github/workflows/build-test-release.yaml b/.github/workflows/build-test-release.yaml
--- a/.github/workflows/build-test-release.yaml
+++ b/.github/workflows/build-test-release.yaml
@@ -41,6 +41,14 @@ jobs:
       - name: Fetch name of whl
         run: |
             echo "FILENAME=$(echo dist/*.whl)" >> $GITHUB_ENV
+
+      - name: upload whl
+        uses: actions/upload-artifact@v4
+        if: success() || failure()
+        with:
+          name: "compressed-tensors-${{ inputs.gitref }}"
+          path: ${FILENAME}
+          retention-days: 7
       
       - name: Install whl
         run: |
@@ -51,10 +59,10 @@ jobs:
               rm -rf src
               make test
 
-      - name: upload whl
-        uses: actions/upload-artifact@v4
-        if: success() || failure()
-        with:
-          name: "compressed-tensors-${{ inputs.gitref }}"
-          path: ${FILENAME}
-          retention-days: 7
+#      - name: upload whl
+#        uses: actions/upload-artifact@v4
+#        if: success() || failure()
+#        with:
+#          name: "compressed-tensors-${{ inputs.gitref }}"
+#          path: ${FILENAME}
+#          retention-days: 7
